/*****************************************************************
 ** @author   STF 470
 ** @version  0.0.1
 ** @purpose  1:22.4, Verify behaviour of port.check(catch) with assignment in case of successful match inside alt
 ** @verdict  pass accept, ttcn3verdict:pass
 *****************************************************************/
module Sem_2204_the_check_operation_090 {

	signature S() exception(integer);
	type port P procedure {
		inout S;
	}

    type component GeneralComp {
		port P p;
	}

	function f() runs on GeneralComp {
		p.getcall;
		setverdict(pass, "Call received");
		p.raise(S, integer:1);
	}

	testcase TC_Sem_2204_the_check_operation_090() runs on GeneralComp system GeneralComp{
		var GeneralComp v_ptc := GeneralComp.create;
		var integer v_par, v_val;
		connect(self:p, v_ptc:p);
		p.call(S:{}, nowait);
		v_ptc.start(f());
        alt
		{
        	[] p.check(catch(S, integer:(0..10)) -> value v_val) {
				if (v_val == 1) { setverdict(pass, "Check operation successful"); }
				else { setverdict(fail, "Incorrect exception value"); }
			}
		}
		p.catch;
		setverdict(pass, "Exception still on the top of the queue");
    }

    control {
        execute(TC_Sem_2204_the_check_operation_090(), 5.0);
    }
}